language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "yimo"
  - git config user.email "1280160831@qq.com"
  - git add .
  - git commit -m "Update blogs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexothemes
env:
 global:
   - GH_REF: github.com/yimogit/yimogit.github.io.git
